// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-designs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/catalog.ts
var SHOP_URL = "https://habibi-amigo.printify.me";
var CONTACT_EMAIL = "habibiamigo@gmail.com";
var SITE_URL = "https://habibiamigo.com";
var DESIGNS = [
  {
    id: "tequila-run-club",
    name: "Tequila Run Club",
    caption: "For the ones who run on tequila.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "secretly-latina",
    name: "Secretly Latina",
    caption: "The secret is out.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "dress-spanish",
    name: "Dress Spanish",
    caption: "Style that speaks Spanish.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "tequila",
    name: "Tequila",
    caption: "One word. One vibe.",
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "vermut",
    name: "Vermut",
    caption: "Sunday afternoons, always.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "ex-fan",
    name: "Ex Fan",
    caption: "Been there, unliked that.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "stay-cool",
    name: "Stay Cool",
    caption: "Rule number one.",
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "no-game",
    name: "No Game",
    caption: "Say it with your chest.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "i-lied",
    name: "I Lied",
    caption: "Honest about the dishonesty.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "asap",
    name: "ASAP",
    caption: "No time like right now.",
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "get-married",
    name: "Get Married? Or Afters?",
    caption: "The eternal question.",
    colors: ["White", "Black", "Navy", "Baby Blue"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  },
  {
    id: "spanish-girls",
    name: "Spanish Girls Are Always Right",
    caption: "It's not up for debate.",
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true
  }
];

// src/lib/mcp/tools/list-designs.ts
var list_designs_default = defineTool({
  name: "list_designs",
  title: "List designs",
  description: "List Habibi Amigo T-shirt designs from the public collection. Optionally filter by name or in-stock status.",
  inputSchema: {
    query: z.string().optional().describe("Case-insensitive substring to match against design name or caption."),
    inStockOnly: z.boolean().optional().describe("When true, return only designs that are currently in stock.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, inStockOnly }) => {
    const q = query?.trim().toLowerCase();
    const results = DESIGNS.filter((d) => {
      if (inStockOnly && !d.inStock) return false;
      if (q && !`${d.name} ${d.caption}`.toLowerCase().includes(q)) return false;
      return true;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { designs: results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-design.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_design_default = defineTool2({
  name: "get_design",
  title: "Get design details",
  description: "Fetch a single Habibi Amigo design by its id.",
  inputSchema: {
    id: z2.string().min(1).describe("Design id, e.g. 'tequila-run-club'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const design = DESIGNS.find((d) => d.id === id);
    if (!design) {
      return {
        content: [{ type: "text", text: `No design found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(design, null, 2) }],
      structuredContent: { design }
    };
  }
});

// src/lib/mcp/tools/shop-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var shop_info_default = defineTool3({
  name: "get_shop_info",
  title: "Get shop info",
  description: "Return the Habibi Amigo shop URL, main site URL, and contact email so a client can direct users to purchase or reach out.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = { shopUrl: SHOP_URL, siteUrl: SITE_URL, contactEmail: CONTACT_EMAIL };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pgcktjgpplbkjfklqrux";
var mcp_default = defineMcp({
  name: "habibi-amigo-mcp",
  title: "Habibi Amigo",
  version: "0.1.0",
  instructions: "Tools for the Habibi Amigo T-shirt brand. Use `list_designs` to browse the collection, `get_design` for details on a single design, and `get_shop_info` for shop and contact links.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_designs_default, get_design_default, shop_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
